Notify.UseService now uses variadic arguments
nikoksr/notify pull request #23
Opened 2021-02-02 21:10 UTC by Karitham

Most of the time, we add services at the start of our applications.

This PR makes it easier by using variadic arguments.

2021-02-03 09:07 UTC, KrishanBhalla approved these changes

2021-02-03 13:33 UTC, nikoksr requested changes
I really like this, great improvement! Appreciate your contribution.

2021-02-03 13:33 UTC, nikoksr commented on use.go
> +func (n *Notify) UseService(service ...Notifier) {
Please change the method name from `UseService` to `UseServices` to match the naming style of the `Notifier.AddReceivers` method.

```suggestion
// UseServices adds the given service(s) to the notifiers services list.
func (n *Notify) UseServices(service ...Notifier) {
```

2021-02-05 13:35 UTC, nikoksr approved these changes

2021-02-05 13:36 UTC, merged