Add support for Plivo
nikoksr/notify pull request #30
Opened 2021-02-06 09:10 UTC by prashanthpai

2021-02-07 11:22 UTC, nikoksr commented
@prashanthpai appreciate your contribution. I will look over it asap. I saw that you have mocked the service, which I find very interesting. We are having a discussion about how we can best test all services reasonably. If you are interested in sharing your experience with us, please tell us here #1.

2021-02-08 22:17 UTC, nikoksr requested changes
Just some small changes recommended by linter and we're ready to merge. Appreciate your contribution.

2021-02-08 22:17 UTC, nikoksr commented on service/plivo/plivo.go
> +func (s *Service) Send(subject string, message string) error {
```suggestion
func (s *Service) Send(subject, message string) error {
```

2021-02-08 22:17 UTC, nikoksr commented on service/plivo/plivo.go
> +		return nil, fmt.Errorf("ClientOptions cannot be nil")
```suggestion
		return nil, fmt.Errorf("client-options cannot be nil")
```

2021-02-08 22:17 UTC, nikoksr commented on service/plivo/plivo.go
> +		return nil, fmt.Errorf("MessageOptions cannot be nil")
```suggestion
		return nil, fmt.Errorf("message-options cannot be nil")
```

2021-02-09 04:05 UTC, ppai-plivo commented on service/plivo/plivo.go
> +func (s *Service) Send(subject string, message string) error {
done

2021-02-09 04:05 UTC, ppai-plivo commented on service/plivo/plivo.go
> +		return nil, fmt.Errorf("ClientOptions cannot be nil")
done

2021-02-09 04:05 UTC, ppai-plivo commented on service/plivo/plivo.go
> +		return nil, fmt.Errorf("MessageOptions cannot be nil")
done

2021-02-09 12:21 UTC, nikoksr approved these changes

2021-02-09 12:21 UTC, merged