feat(service): Add line service
nikoksr/notify pull request #53
Opened 2021-02-23 10:21 UTC by yoelsusanto

Changelog:
- Add line service implementation
- Add line service on main readme
- Add line service usage example

Closes: #27

2021-02-28 13:32 UTC, nikoksr requested changes
Appreciate your contribution! Just some minor changes and pretty much all related to code style. I would say tests are missing but since most are done yet anyway, I think its better when all missing tests will be done at the same time. So yeah, good job but please fix the minor change requests.

2021-02-28 13:32 UTC, nikoksr commented on service/line/usage.md
> +  )
```suggestion
  err := notifier.Send(
    context.Background(),
    "Welcome",
    "I am a bot written in Go!",
  )
```

2021-02-28 13:32 UTC, nikoksr commented on service/line/usage.md
> +  // Tell our notifier to use the line service. You can repeat the above process
```suggestion
  notifier := notify.New()
  
  // Tell our notifier to use the line service. You can repeat the above process
```

2021-02-28 13:32 UTC, nikoksr commented on service/line/line.go
> +	return l, nil
```suggestion
	}
	
	return l, nil
```

2021-02-28 13:32 UTC, nikoksr commented on service/line/line.go
> +		default:
```suggestion
			return ctx.Err()
		default:
```

2021-02-28 13:32 UTC, nikoksr commented on service/line/line.go
> +				return errors.Wrapf(err, "failed to send message to line. destination id: '%s'", destinationID)
```suggestion
				return errors.Wrapf(err, "failed to send message to LINE contact '%s'", receiverID)
```

2021-03-06 10:05 UTC, nikoksr commented
Hey @yoelsusanto, I just wanted to check in and see if maybe you need help with something or one of my instructions might not be completely understandable. Just let me know if I can help you in any way.

2021-03-06 14:19 UTC, yoelsusanto commented
> Hey @yoelsusanto, I just wanted to check in and see if maybe you need help with something or one of my instructions might not be completely understandable. Just let me know if I can help you in any way.

Hi @nikoksr, your instruction has been clear. I just added your requested changes. Let me know if you need anything else.

2021-03-09 17:06 UTC, nikoksr approved these changes
Great, thanks for your contribution and applied changes.

2021-03-09 17:07 UTC, merged