Add Service rocketchat
nikoksr/notify pull request #56
Opened 2021-03-10 17:45 UTC by kha7iq

Changelog:

    Implement RocketChat service
    Update readme to include the service.
    Add usage example

Closes: https://github.com/nikoksr/notify/issues/26

2021-03-15 00:26 UTC, nikoksr requested changes
@kha7iq great job, very much appreciate your contribution. Please just apply my minor style recommendations.

2021-03-15 00:26 UTC, nikoksr commented on service/rocketchat/rocketchat.go
> +	chNames []string
```suggestion
	channelNames []string
```

2021-03-15 00:26 UTC, nikoksr commented on service/rocketchat/rocketchat.go
> +func (r *RocketChat) AddReceivers(chNames ...string) {
```suggestion
func (r *RocketChat) AddReceivers(channelNames ...string) {
```

2021-03-15 00:26 UTC, nikoksr commented on service/rocketchat/rocketchat.go
> +	for _, chName := range r.chNames {
```suggestion
	for _, channelName := range r.channelNames {
```

2021-03-15 00:26 UTC, nikoksr commented on service/rocketchat/rocketchat.go
> +	chNames []string
Please apply for the remaining use cases.

2021-03-15 03:57 UTC, kha7iq commented
@nikoksr  I have update the code with style recommendations , do let me know if there is anything else.
And thank you for your work

2021-03-16 00:48 UTC, nikoksr approved these changes
Appreciate your work and kind words :rocket:

2021-03-16 01:03 UTC, merged