add: textmagic service
nikoksr/notify pull request #92
Opened 2021-05-06 14:56 UTC by himsngh

#82 
(Textmagic wasn't available in my country so I was not able to test it. Hope that's fine and if there are any issues please do let me know I will try to solve that)

2021-05-25 16:26 UTC, nikoksr requested changes
@himsngh I am very grateful to you for your contribution. It really helps us. There are unfortunately a few changes that need to be done and we definitely need to test the service before we can merge it. I'll see if I can find time to do that, otherwise it would be really great if someone else could do it.

2021-05-25 16:26 UTC, nikoksr commented on service/textmagic/textmagic.go
> +	tm "github.com/textmagic/textmagic-rest-go-v2/v2"
```suggestion
	textMagic "github.com/textmagic/textmagic-rest-go-v2/v2"
```

2021-05-25 16:26 UTC, nikoksr commented on service/textmagic/textmagic.go
> +}
```suggestion
// Service allow you to configure a TextMagic SDK client.
type Service struct {
	userName           string
 	apiKey             string
	phoneNumbers       []string
 	client *textMagic.APIClient
}
```

2021-05-25 16:26 UTC, nikoksr commented on service/textmagic/textmagic.go
> +}
```suggestion
// New creates a new text magic client. Use your user-name and API key from
// https://my.textmagic.com/online/api/rest-api/keys.
func New(userName, apiKey string) *Service {
	config := textMagic.NewConfiguration()
	client := textMagic.NewAPIClient(config)

	return &Service{
		client: client,
		userName:           userName,
		apiKey:             apiKey,
	}
}
```

2021-05-25 16:26 UTC, nikoksr commented on service/textmagic/textmagic.go
> +}
```suggestion
// AddReceivers adds the given phone numbers to the notifier.
func (s *Service) AddReceivers(phoneNumbers ...string) {
	s.phoneNumbers = append(s.phoneNumbers, phoneNumbers...)
}
```

2021-05-25 16:26 UTC, nikoksr commented on service/textmagic/textmagic.go
> +}
```suggestion
// Send sends a SMS via textmagic to all previously added receivers.
func (s *Service) Send(ctx context.Context, subject, message string) error {
	auth := context.WithValue(ctx, textMagic.ContextBasicAuth, textMagic.BasicAuth{
		UserName: s.userName,
		Password: s.apiKey,
	})

	text := subject + "\n" + message
	_, _, err := s.textMagicAPIClient.TextMagicApi.SendMessage(auth, textMagic.SendMessageInputObject{
		Text:   text,
		Phones: strings.Join(s.phoneNumbers, ","),
	})

	return err
}
```

2021-05-25 16:26 UTC, nikoksr commented on service/textmagic/textmagic.go
> +	tm "github.com/textmagic/textmagic-rest-go-v2/v2"
Make package name more expressive.

2021-05-25 16:26 UTC, nikoksr commented on service/textmagic/textmagic.go
> +}
Core struct should be called `Service` and none of its fields need to be exported.

2021-05-25 16:26 UTC, nikoksr commented on service/textmagic/textmagic.go
> +}
Function should just be called `New`; `textmagic.New()` is less redundant than `textmagic.NewTextMagicClient()`. Also, applying the new field names and moving comment about username and api key from `Send` method to here.

2021-05-25 16:26 UTC, nikoksr commented on service/textmagic/textmagic.go
> +}
We're already receiving a `context.Context` from the method's arguments and thus don't need to create a new one via `context.Background()`. 

Additionally apply new field names of `Service` struct and remove unnecessary error evaluation at the end of the method.

2021-05-25 16:26 UTC, nikoksr commented on service/textmagic/Readme.md
> +  log.Printf("notification sent")
```suggestion
  textMagicService := textmagic.New("YOUR_USER_NAME", "YOUR_API_KEY")

  textMagicService.AddReceivers("Destination1-Phone-Number")

  notifier := notify.New()
  notifier.UseServices(textMagicService)

  err := notifier.Send(context.Background(), "subject", "message")
  if err != nil {
    log.Fatalf("notifier.Send() failed: %v", err)
  }

  log.Printf("notification sent")
```

2021-05-25 16:26 UTC, nikoksr commented on service/textmagic/Readme.md
> +  log.Printf("notification sent")
Apply new function names and do a little clean-up.

2021-05-26 09:37 UTC, himsngh commented
> @himsngh I am very grateful to you for your contribution. It really helps us. There are unfortunately a few changes that need to be done and we definitely need to test the service before we can merge it. I'll see if I can find time to do that, otherwise it would be really great if someone else could do it.

@nikoksr  I have done the changes.

2021-05-26 12:07 UTC, nikoksr approved these changes
Appreciate the changes and your contribution!

2021-05-26 12:08 UTC, merged